### ISSUE TITLE
Lockpicking in professions dashboard

### ISSUE THREAD

**Issue by kriberg** [Benik/BenikUI-Classic#2]
Hey, would it be possible to add the lockpicking skill to the professions dashboard? It's not available from the list in options currently.

**Comment by Benik** [comment]
Can you please post a screenshot of how the Player Skills list looks like with Lockpicking?

**Comment by kriberg** [comment]
![image](https://user-images.githubusercontent.com/2341/233827015-f0fd9e94-213e-436e-85d3-d1a410e1eaf1.png)

**Comment by Benik** [comment]
hmm yes, thought so. You see that Lockpicking is on the Class Skills list, that I filter out, so that only professions will show. Because  Blizzard's api for professions is totally different in Classic - in fact there's barely no api for it - the professions dashboard scans the above list to grab the Professions. It would be hard to grab only Lockpicking.

**Comment by kriberg** [comment]
Aight, too bad
